"""Imports every model module so SQLAlchemy metadata is fully populated.

``Base.metadata.create_all`` and Alembic autogenerate rely on this module being
imported before the metadata is inspected.
"""

from app.models.accounting import (  # noqa: F401
    Account,
    AccountingDimensionValue,
    AccountingPeriodClose,
    CustomerLedgerEntry,
    JournalEntry,
    JournalEntryLine,
    LedgerDocumentLink,
    PostingRule,
    SupplierLedgerEntry,
)
from app.models.assets import (  # noqa: F401
    Asset,
    AssetCategory,
    AssetDepreciation,
    AssetDisposal,
    AssetMaintenance,
    AssetTransfer,
)
from app.models.base import Base  # noqa: F401
from app.models.crm import (  # noqa: F401
    Activity,
    Lead,
    LeadSource,
    LostReason,
    Opportunity,
    PipelineStage,
    SalesTarget,
)
from app.models.expenses import (  # noqa: F401
    Budget,
    BudgetLine,
    Expense,
    ExpenseAdvance,
    ExpenseCategory,
    ExpenseClaim,
    ExpenseLine,
)
from app.models.hr import (  # noqa: F401
    AttendanceRecord,
    Employee,
    EmployeeLoan,
    EmployeeSalaryComponent,
    EmployeeShiftAssignment,
    EmploymentContract,
    Holiday,
    LeaveBalance,
    LeaveRequest,
    LeaveType,
    PayrollPeriod,
    PayrollRun,
    Payslip,
    PayslipLine,
    Position,
    SalaryComponent,
    WorkShift,
)
from app.models.identity import (  # noqa: F401
    Attachment,
    AuditLog,
    BackupJob,
    ImportJob,
    ImportJobRow,
    LoginAttempt,
    Notification,
    NotificationPreference,
    OutboxMessage,
    PasswordResetToken,
    Permission,
    Role,
    RolePermission,
    SavedReport,
    User,
    UserBranchAccess,
    UserCompanyAccess,
    UserRole,
    UserSession,
    UserWarehouseAccess,
)
from app.models.inventory import (  # noqa: F401
    Batch,
    InventoryValuationLayer,
    ReorderRule,
    SerialNumber,
    StockAdjustment,
    StockAdjustmentLine,
    StockBalance,
    StockCount,
    StockCountLine,
    StockLedgerEntry,
    StockMovementTemplate,
    StockTransfer,
    StockTransferLine,
)
from app.models.manufacturing import (  # noqa: F401
    Bom,
    BomLine,
    BomOperation,
    ProductionCostSheet,
    ProductionOperation,
    ProductionOrder,
    ProductionOrderMaterial,
    ProductionOutput,
    Routing,
    RoutingOperation,
    WorkCenter,
)
from app.models.masterdata import (  # noqa: F401
    Brand,
    Contact,
    Customer,
    CustomerGroup,
    PartyStatusHistory,
    PriceList,
    PriceListItem,
    Product,
    ProductBarcode,
    ProductCategory,
    ProductUnit,
    Supplier,
    SupplierGroup,
    SupplierPriceHistory,
    SupplierProduct,
    Warehouse,
    WarehouseLocation,
    WarehouseZone,
)
from app.models.platform import (  # noqa: F401
    Address,
    Branch,
    City,
    Company,
    CostCenter,
    Country,
    Currency,
    Department,
    Division,
    DocumentType,
    ExchangeRate,
    FiscalPeriod,
    FiscalYear,
    KitItem,
    ModuleActivation,
    NumberSequence,
    PaymentTerm,
    SystemSetting,
    Tax,
    UnitConversion,
    UnitGroup,
    UnitOfMeasure,
)
from app.models.projects import (  # noqa: F401
    Milestone,
    Project,
    ProjectBillingSchedule,
    ProjectPhase,
    ProjectResourcePlan,
    ProjectTask,
    Timesheet,
    TimesheetLine,
)
from app.models.purchasing import (  # noqa: F401
    DebitNote,
    DebitNoteLine,
    GoodsReceipt,
    GoodsReceiptLine,
    PurchaseInvoice,
    PurchaseInvoiceLine,
    PurchaseOrder,
    PurchaseOrderLine,
    PurchaseRequest,
    PurchaseRequestLine,
    Rfq,
    RfqLine,
    RfqSupplier,
    SupplierEvaluation,
    SupplierQuotation,
    SupplierQuotationLine,
)
from app.models.sales import (  # noqa: F401
    CreditNote,
    CreditNoteLine,
    DeliveryNote,
    DeliveryNoteLine,
    PosCashMovement,
    PosPayment,
    PosShift,
    PosTerminal,
    Quotation,
    QuotationLine,
    SalesCommission,
    SalesInvoice,
    SalesInvoiceLine,
    SalesOrder,
    SalesOrderLine,
)
from app.models.service import (  # noqa: F401
    ServiceContract,
    ServiceContractAsset,
    ServiceRequest,
    TechnicianSchedule,
    Ticket,
    TicketMessage,
    Warranty,
    WorkOrder,
    WorkOrderLabor,
    WorkOrderPart,
)
from app.models.treasury import (  # noqa: F401
    BankAccount,
    BankReconciliation,
    BankReconciliationLine,
    CashAccount,
    CashFlowSnapshot,
    Cheque,
    CurrencyRevaluation,
    Payment,
    PaymentAllocation,
    TreasuryTransfer,
)
from app.models.workflow import (  # noqa: F401
    ApprovalDelegation,
    WorkflowAction,
    WorkflowConditionTemplate,
    WorkflowDefinition,
    WorkflowInstance,
    WorkflowStep,
)

__all__ = ["Base"]
